version: '3'
services:
# Nginx Service
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/public/
      - ./nginx/conf.d/:/etc/nginx/conf.d/

# PHP
  php:
    image: php:fpm-alpine3.18
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./www/:/var/www/public/
